### PR TITLE
Rework mouse hover simulation

### PR DESCRIPTION
**Pull request by laplamgor**
As you may already know, many UI interactions in KC rely on mouse hover.

The existing fix only overrides some object events which is hit and miss and not ideal. Here is a new implementation completely reworked in JavaScript and injected into KC game client `main.js`. It works as a global solution so there is no need to deal with each interaction problem individually.

### Event mapping

Realistically, there is no perfect one-to-one event mapping for mouse and touch. In order to enable interaction scenarios such as clicking a button on top of a pop up bubble, I use the following methods:
- As soon as the user start touching an object, `mouseover` is triggered on that object.
- When the finger moves to another object, `mouseout` is triggered on the previous object.
- When the finger leaves the screen, **NO** `mouseout` is triggered.

So alert bubbles still persist until you tap the background or something else.

### Fixed behaviors
1. The effect of pressing each button in the port does not disappear or improvement arsenal button does not appear (https://antest1.github.io/GotoBrowser/howto.html)
2. Alert is not displayed when the limit is reached during development/construction (https://antest1.github.io/GotoBrowser/howto.html)
3. Preset detail bubble and alert bubble not shown (issue https://github.com/antest1/GotoBrowser/issues/1)
4. Preset list keeps scrolling (issue https://github.com/antest1/GotoBrowser/issues/32)
5. Warning not shown when trying to resupply without enough resource

... and more

### Warning
This patch also breaks the hover behavior of a physical mouse with WebView 58+. It is because I actually changed the event names. However, I guess not many people use a physical mouse on Android anyway.

### CODE REVIEW

**Comment by antest1** [comment]
Good works, thanks for contribution!

**Comment by antest1** [comment]
Seems that buttons on the port works when double-click, is this an intended behavior?

**Comment by laplamgor** [comment]
Those buttons in the port is poorly designed by C2. Their interaction logic is different from all other buttons in-game. I don't find any global solution to make those buttons single-tapable without hard-coding specifically for them or breaking behaviors elsewhere.

**Comment by antest1** [comment]
solved in c31d324.

**Pull request merged**
